apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisperwealth-data
  namespace: whisperwealth
  labels:
    app: whisperwealth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
